# Generated by Django 5.2.16 on 2026-07-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('budget', models.CharField(blank=True, max_length=50)),
                ('destination_country', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('reference_photo', models.ImageField(blank=True, null=True, upload_to='orders/%Y/%m/')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('sourcing', 'Sourcing'), ('purchased', 'Purchased'), ('in_transit', 'In transit'), ('delivered', 'Delivered')], default='requested', max_length=20)),
                ('shopper', models.CharField(blank=True, max_length=100)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('sourcing', 'Sourcing'), ('purchased', 'Purchased'), ('in_transit', 'In transit'), ('delivered', 'Delivered')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
